=== Hawkbat/OuterWildsRPG/schemas/drop.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "DropData",
  "type": "object",
  "description": "An inventory item (not to be confused with vanilla items) that can be picked up and interacted with via the ship's inventory menu.",
  "additionalProperties": false,
  "required": [
    "id",
    "name"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique internal identifier for this entity. This must not be the same as any other entity of the same type in your mod.",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "description": "The name to display in-game for this entity.",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "description": "A short description to display in the inventory for this drop."
    },
    "rarity": {
      "description": "The 'quality' rating of this drop, which generally reflects its value.",
      "$ref": "#/definitions/DropRarity"
    },
    "equipSlot": {
      "description": "Which equipment slot this drop can be equipped to, if any. Mutually exclusive with consumable.",
      "$ref": "#/definitions/EquipSlot"
    },
    "consumable": {
      "type": "boolean",
      "description": "Whether this item can be consumed, removing it from the player's inventory. Mutually exclusive with equipSlot."
    },
    "duration": {
      "type": "number",
      "description": "How long the effects of this drop's buffs will last after being consumed, in seconds.",
      "format": "float"
    },
    "iconPath": {
      "type": "string",
      "description": "A file path (relative to your mod's folder) to an image file to use for this drop's icon. Can be shared with other drops."
    },
    "pickUpAudioType": {
      "type": "string",
      "description": "An Outer Wilds AudioType value that will be played when the drop is picked up. See https://nh.outerwildsmods.com/reference/audio_enum.html"
    },
    "consumeAudioType": {
      "type": "string",
      "description": "An Outer Wilds AudioType value that will be played when the drop is consumed. See https://nh.outerwildsmods.com/reference/audio_enum.html"
    },
    "buffs": {
      "type": "array",
      "description": "Effects that will apply while this drop is equipped.",
      "items": {
        "$ref": "#/definitions/BuffData"
      }
    },
    "locations": {
      "type": "array",
      "description": "Locations in the solar system to place pickups for this drop.",
      "items": {
        "$ref": "#/definitions/DropLocationData"
      }
    }
  },
  "definitions": {
    "DropRarity": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "Common",
        "Uncommon",
        "Rare",
        "Epic",
        "Legendary"
      ],
      "enum": [
        "common",
        "uncommon",
        "rare",
        "epic",
        "legendary"
      ]
    },
    "EquipSlot": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "None",
        "Helmet",
        "Suit",
        "Jetpack",
        "Scout",
        "Launcher",
        "Signalscope",
        "Flashlight",
        "Translator",
        "Radio",
        "Stick"
      ],
      "enum": [
        "none",
        "helmet",
        "suit",
        "jetpack",
        "scout",
        "launcher",
        "signalscope",
        "flashlight",
        "translator",
        "radio",
        "stick"
      ]
    },
    "BuffData": {
      "type": "object",
      "description": "Various possible effects that will apply when the buff is active.",
      "additionalProperties": false,
      "properties": {
        "hazardDamage": {
          "description": "Modifies the damage the player takes from various types of hazards.",
          "$ref": "#/definitions/HazardDamageEffectData"
        },
        "translationSpeed": {
          "description": "Modifies the speed at which the player can translate Nomai text.",
          "$ref": "#/definitions/TranslationSpeedEffectData"
        },
        "travelMusic": {
          "description": "Changes the travel music played when flying the ship between planets.",
          "$ref": "#/definitions/TravelMusicEffectData"
        },
        "heal": {
          "description": "Restores a percentage of the player's health.",
          "$ref": "#/definitions/HealEffectData"
        },
        "giveDrop": {
          "description": "Adds a drop directly to the player's inventory.",
          "$ref": "#/definitions/GiveDropEffectData"
        },
        "custom": {
          "description": "Defines a custom effect that can be interacted with via the mod API.",
          "$ref": "#/definitions/CustomEffectData"
        }
      }
    },
    "HazardDamageEffectData": {
      "type": "object",
      "description": "Modifies the damage the player takes from various types of hazards.",
      "additionalProperties": false,
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "description": "The type of hazard to modify damage for.",
          "$ref": "#/definitions/HazardType"
        },
        "add": {
          "type": "number",
          "description": "The percentage of the initial damage to add/reduce. E.g. a value of -0.1 means subtract 10% of the base damage from the total.",
          "format": "float"
        },
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total damage by. E.g. a value of 0.25 will result in 25% damage, or a 75% reduction.",
          "format": "float"
        }
      }
    },
    "HazardType": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "All",
        "General",
        "GhostMatter",
        "Heat",
        "Fire",
        "Sandfall",
        "Electricity"
      ],
      "enum": [
        "all",
        "general",
        "ghostMatter",
        "heat",
        "fire",
        "sandfall",
        "electricity"
      ]
    },
    "TranslationSpeedEffectData": {
      "type": "object",
      "description": "Modifies the speed at which the player can translate Nomai text.",
      "additionalProperties": false,
      "properties": {
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total translation time by. E.g. a value of 0.25 will result in translating taking 25% of the usual time, or a 75% reduction.",
          "format": "float"
        }
      }
    },
    "TravelMusicEffectData": {
      "type": "object",
      "description": "Changes the travel music played when flying the ship between planets.",
      "additionalProperties": false,
      "required": [
        "audioType"
      ],
      "properties": {
        "audioType": {
          "type": "string",
          "description": "An Outer Wilds AudioType value that will be used as the travel music will this buff is active. See https://nh.outerwildsmods.com/reference/audio_enum.html",
          "minLength": 1
        }
      }
    },
    "HealEffectData": {
      "type": "object",
      "description": "Restores a percentage of the player's health.",
      "additionalProperties": false,
      "required": [
        "amount"
      ],
      "properties": {
        "amount": {
          "type": "number",
          "description": "The percentage of total health to restore. E.g. 0.2 will restore 20% of maximum health.",
          "format": "float"
        }
      }
    },
    "GiveDropEffectData": {
      "type": "object",
      "description": "Adds a drop directly to the player's inventory.",
      "additionalProperties": false,
      "required": [
        "drop"
      ],
      "properties": {
        "drop": {
          "type": "string",
          "description": "The unique ID of the drop to give.",
          "minLength": 1
        },
        "amount": {
          "type": "integer",
          "description": "The text to display in the UI for this effect.",
          "format": "int32"
        }
      }
    },
    "CustomEffectData": {
      "type": "object",
      "description": "Defines a custom effect that can be interacted with via the mod API.",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "A custom value that uniquely identifies this effect, for use with the mod API."
        },
        "description": {
          "type": "string",
          "description": "The text to display in the UI for this effect."
        }
      }
    },
    "DropLocationData": {
      "type": "object",
      "description": "A location in the solar system where this drop can be picked up by the player.",
      "additionalProperties": false,
      "required": [
        "parentPath"
      ],
      "properties": {
        "parentPath": {
          "type": "string",
          "description": "The full path to a GameObject in the solar system that the drop should be attached to.",
          "minLength": 1
        },
        "position": {
          "description": "The position to place the drop at.",
          "$ref": "#/definitions/Vector3Data"
        },
        "rotation": {
          "description": "The rotation of the drop.",
          "$ref": "#/definitions/Vector3Data"
        },
        "isRelativeToParent": {
          "type": "boolean",
          "description": "Whether the position and rotation are relative to the parent, instead of the whole planet."
        },
        "alignRadial": {
          "type": [
            "boolean",
            "null"
          ],
          "description": "Whether to orient the drop to point 'up' away from the center of the planet, or use the provided rotation value. Defaults to true if `rotation` is omitted and false otherwise."
        },
        "respawns": {
          "type": "boolean",
          "description": "Whether this drop respawns at the start of every loop."
        },
        "visuals": {
          "type": "array",
          "description": "Full paths to GameObjects to disable when picking up this drop.",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Vector3Data": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "x": {
          "type": "number",
          "format": "float"
        },
        "y": {
          "type": "number",
          "format": "float"
        },
        "z": {
          "type": "number",
          "format": "float"
        }
      }
    }
  }
}

=== Hawkbat/OuterWildsRPG/drops/radio_timberhearth.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "RADIO_TIMBERHEARTH",
  "name": "Timber Hearth Cassette",
  "description": "A cassette tape for your ship's radio that reminds you of the village on Timber Hearth.",
  "rarity": "uncommon",
  "equipSlot": "radio",
  "iconPath": "RECORDER.png",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH",
      "position": {
        "x": -49.51757,
        "y": -31.45731,
        "z": 218.7875
      }
    }
  ],
  "buffs": [
    { "travelMusic": { "audioType": "TH_Village" } }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/basic_translator.json
{
  "$schema": "https://raw.githubusercontent.com/Hawkbat/OuterWildsRPG/main/schemas/drop.schema.json",
  "id": "BASIC_TRANSLATOR",
  "name": "Nomai Translator",
  "description": "A tool you and Hal developed to translate Nomai writing.",
  "rarity": "uncommon",
  "equipSlot": "translator",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH",
      "position": {
        "x": -70.33205,
        "y": 5.372261,
        "z": 213.8982
      },
      "rotation": {
        "x": 0.4891755,
        "y": 72.73146,
        "z": 88.94646
      }
    }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/marshmallow_can.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "MARSHMALLOW_CAN",
  "name": "Marshmallow Can",
  "description": "A full can of marshmallows! Who makes these, anyway?",
  "rarity": "uncommon",
  "consumable": true,
  "iconPath": "MARSHMALLOW_CAN_OPEN.png",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH/Sector_Village/Sector_StartingCamp/Props_StartingCamp/OtherComponentsGroup/Props_HEA_CampsiteLogAssets",
      "position": {
        "x": -0.158,
        "y": 0.068,
        "z": -1.628
      },
      "isRelativeToParent": true,
      "respawns": true,
      "visuals": [
        "TimberHearth_Body/Sector_TH/Sector_Village/Sector_StartingCamp/Props_StartingCamp/OtherComponentsGroup/Props_HEA_CampsiteLogAssets/Props_HEA_MarshmallowCanOpened"
      ]
    }
  ],
  "buffs": [
    {
      "giveDrop": {
        "drop": "MARSHMALLOW",
        "amount": 5
      }
    }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/radio_hideandseek.json
{
  "$schema": "https://raw.githubusercontent.com/Hawkbat/OuterWildsRPG/main/schemas/drop.schema.json",
  "id": "RADIO_HIDEANDSEEK",
  "name": "Cassette - Campfire Tune",
  "description": "A cassette tape for your ship's radio that plays a catchy tune.",
  "rarity": "uncommon",
  "equipSlot": "radio",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH",
      "position": {
        "x": -34.81908,
        "y": -10.66688,
        "z": 191.5841
      },
      "rotation": {
        "x": 273.4768,
        "y": 11.40733,
        "z": 158.3292
      }
    }
  ],
  "buffs": [

  ]
}

=== Hawkbat/OuterWildsRPG/drops/basic_signalscope.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "BASIC_SIGNALSCOPE",
  "name": "Hatchling's Signalscope",
  "description": "A tool for picking up audible signals from distant locations.",
  "rarity": "uncommon",
  "equipSlot": "signalscope",
  "iconPath": "SIGNALSCOPE.png",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH/Sector_Village/Sector_LowerVillage/Props_LowerVillage/OtherComponentsGroup/Architecture_LowerVillage/OtherComponentsGroup/Village_UnderLaunchTowerProps/LaunchTowerSequoiaProps/WorkBench2/Props_HEA_Signalscope (2)",
      "rotation": {
        "x": 285,
        "y": 270,
        "z": 0
      },
      "isRelativeToParent": true,
      "visuals": [
        "TimberHearth_Body/Sector_TH/Sector_Village/Sector_LowerVillage/Props_LowerVillage/OtherComponentsGroup/Architecture_LowerVillage/BatchedGroup/BatchedMeshRenderers_11"
      ]
    }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/basic_flashlight.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "BASIC_FLASHLIGHT",
  "name": "Hatchling's Flashlight",
  "description": "A standard hand-held flashlight. Great for nighttime exploration!",
  "rarity": "uncommon",
  "equipSlot": "flashlight",
  "iconPath": "FLASHLIGHT.png",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH",
      "position": {
        "x": 21.052,
        "y": -46.43467,
        "z": 183.9364
      },
      "visuals": []
    }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/radio_observatory.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "RADIO_OBSERVATORY",
  "name": "Observatory Cassette",
  "description": "A cassette tape for your ship's radio that reminds you of the Hearthian observatory.",
  "rarity": "uncommon",
  "equipSlot": "radio",
  "iconPath": "RECORDER.png",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH",
      "position": {
        "x": -53.54003,
        "y": -6.385822,
        "z": 231.0816
      }
    }
  ],
  "buffs": [
    { "travelMusic": { "audioType": "TH_Observatory" } }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/sapwine.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "SAPWINE",
  "name": "Porphy's Sap Wine",
  "description": "A serving of Porphy's infamous sap wine. This batch was brewed to commemorate your first launch!",
  "rarity": "common",
  "consumable": true,
  "iconPath": "SOUP.png",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH/Sector_Village/Sector_LowerVillage/Characters_LowerVillage/Villager_HEA_Porphy/Props_HEA_SapwinePot",
      "position": {
        "x": 7.100058,
        "y": -15.95331,
        "z": 187.5071
      },
      "visuals": [],
      "respawns": true
    }
  ],
  "buffs": [
    {
      "heal": { "amount": 0.5 }
    }
  ]
}
