=== Hawkbat/OuterWildsRPG/schemas/drop.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "DropData",
  "type": "object",
  "description": "An inventory item (not to be confused with vanilla items) that can be picked up and interacted with via the ship's inventory menu.",
  "additionalProperties": false,
  "required": [
    "id",
    "name"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique internal identifier for this entity. This must not be the same as any other entity of the same type in your mod.",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "description": "The name to display in-game for this entity.",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "description": "A short description to display in the inventory for this drop."
    },
    "rarity": {
      "description": "The 'quality' rating of this drop, which generally reflects its value.",
      "$ref": "#/definitions/DropRarity"
    },
    "equipSlot": {
      "description": "Which equipment slot this drop can be equipped to, if any. Mutually exclusive with consumable.",
      "$ref": "#/definitions/EquipSlot"
    },
    "consumable": {
      "type": "boolean",
      "description": "Whether this item can be consumed, removing it from the player's inventory. Mutually exclusive with equipSlot."
    },
    "duration": {
      "type": "number",
      "description": "How long the effects of this drop's buffs will last after being consumed, in seconds.",
      "format": "float"
    },
    "iconPath": {
      "type": "string",
      "description": "A file path (relative to your mod's folder) to an image file to use for this drop's icon. Can be shared with other drops."
    },
    "pickUpAudioType": {
      "type": "string",
      "description": "An Outer Wilds AudioType value that will be played when the drop is picked up. See https://nh.outerwildsmods.com/reference/audio_enum.html"
    },
    "consumeAudioType": {
      "type": "string",
      "description": "An Outer Wilds AudioType value that will be played when the drop is consumed. See https://nh.outerwildsmods.com/reference/audio_enum.html"
    },
    "buffs": {
      "type": "array",
      "description": "Effects that will apply while this drop is equipped.",
      "items": {
        "$ref": "#/definitions/BuffData"
      }
    },
    "locations": {
      "type": "array",
      "description": "Locations in the solar system to place pickups for this drop.",
      "items": {
        "$ref": "#/definitions/DropLocationData"
      }
    }
  },
  "definitions": {
    "DropRarity": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "Common",
        "Uncommon",
        "Rare",
        "Epic",
        "Legendary"
      ],
      "enum": [
        "common",
        "uncommon",
        "rare",
        "epic",
        "legendary"
      ]
    },
    "EquipSlot": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "None",
        "Helmet",
        "Suit",
        "Jetpack",
        "Scout",
        "Launcher",
        "Signalscope",
        "Flashlight",
        "Translator",
        "Radio",
        "Stick"
      ],
      "enum": [
        "none",
        "helmet",
        "suit",
        "jetpack",
        "scout",
        "launcher",
        "signalscope",
        "flashlight",
        "translator",
        "radio",
        "stick"
      ]
    },
    "BuffData": {
      "type": "object",
      "description": "Various possible effects that will apply when the buff is active.",
      "additionalProperties": false,
      "properties": {
        "hazardDamage": {
          "description": "Modifies the damage the player takes from various types of hazards.",
          "$ref": "#/definitions/HazardDamageEffectData"
        },
        "translationSpeed": {
          "description": "Modifies the speed at which the player can translate Nomai text.",
          "$ref": "#/definitions/TranslationSpeedEffectData"
        },
        "travelMusic": {
          "description": "Changes the travel music played when flying the ship between planets.",
          "$ref": "#/definitions/TravelMusicEffectData"
        },
        "heal": {
          "description": "Restores a percentage of the player's health.",
          "$ref": "#/definitions/HealEffectData"
        },
        "giveDrop": {
          "description": "Adds a drop directly to the player's inventory.",
          "$ref": "#/definitions/GiveDropEffectData"
        },
        "custom": {
          "description": "Defines a custom effect that can be interacted with via the mod API.",
          "$ref": "#/definitions/CustomEffectData"
        }
      }
    },
    "HazardDamageEffectData": {
      "type": "object",
      "description": "Modifies the damage the player takes from various types of hazards.",
      "additionalProperties": false,
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "description": "The type of hazard to modify damage for.",
          "$ref": "#/definitions/HazardType"
        },
        "add": {
          "type": "number",
          "description": "The percentage of the initial damage to add/reduce. E.g. a value of -0.1 means subtract 10% of the base damage from the total.",
          "format": "float"
        },
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total damage by. E.g. a value of 0.25 will result in 25% damage, or a 75% reduction.",
          "format": "float"
        }
      }
    },
    "HazardType": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "All",
        "General",
        "GhostMatter",
        "Heat",
        "Fire",
        "Sandfall",
        "Electricity"
      ],
      "enum": [
        "all",
        "general",
        "ghostMatter",
        "heat",
        "fire",
        "sandfall",
        "electricity"
      ]
    },
    "TranslationSpeedEffectData": {
      "type": "object",
      "description": "Modifies the speed at which the player can translate Nomai text.",
      "additionalProperties": false,
      "properties": {
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total translation time by. E.g. a value of 0.25 will result in translating taking 25% of the usual time, or a 75% reduction.",
          "format": "float"
        }
      }
    },
    "TravelMusicEffectData": {
      "type": "object",
      "description": "Changes the travel music played when flying the ship between planets.",
      "additionalProperties": false,
      "required": [
        "audioType"
      ],
      "properties": {
        "audioType": {
          "type": "string",
          "description": "An Outer Wilds AudioType value that will be used as the travel music will this buff is active. See https://nh.outerwildsmods.com/reference/audio_enum.html",
          "minLength": 1
        }
      }
    },
    "HealEffectData": {
      "type": "object",
      "description": "Restores a percentage of the player's health.",
      "additionalProperties": false,
      "required": [
        "amount"
      ],
      "properties": {
        "amount": {
          "type": "number",
          "description": "The percentage of total health to restore. E.g. 0.2 will restore 20% of maximum health.",
          "format": "float"
        }
      }
    },
    "GiveDropEffectData": {
      "type": "object",
      "description": "Adds a drop directly to the player's inventory.",
      "additionalProperties": false,
      "required": [
        "drop"
      ],
      "properties": {
        "drop": {
          "type": "string",
          "description": "The unique ID of the drop to give.",
          "minLength": 1
        },
        "amount": {
          "type": "integer",
          "description": "The text to display in the UI for this effect.",
          "format": "int32"
        }
      }
    },
    "CustomEffectData": {
      "type": "object",
      "description": "Defines a custom effect that can be interacted with via the mod API.",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "A custom value that uniquely identifies this effect, for use with the mod API."
        },
        "description": {
          "type": "string",
          "description": "The text to display in the UI for this effect."
        }
      }
    },
    "DropLocationData": {
      "type": "object",
      "description": "A location in the solar system where this drop can be picked up by the player.",
      "additionalProperties": false,
      "required": [
        "parentPath"
      ],
      "properties": {
        "parentPath": {
          "type": "string",
          "description": "The full path to a GameObject in the solar system that the drop should be attached to.",
          "minLength": 1
        },
        "position": {
          "description": "The position to place the drop at.",
          "$ref": "#/definitions/Vector3Data"
        },
        "rotation": {
          "description": "The rotation of the drop.",
          "$ref": "#/definitions/Vector3Data"
        },
        "isRelativeToParent": {
          "type": "boolean",
          "description": "Whether the position and rotation are relative to the parent, instead of the whole planet."
        },
        "alignRadial": {
          "type": [
            "boolean",
            "null"
          ],
          "description": "Whether to orient the drop to point 'up' away from the center of the planet, or use the provided rotation value. Defaults to true if `rotation` is omitted and false otherwise."
        },
        "respawns": {
          "type": "boolean",
          "description": "Whether this drop respawns at the start of every loop."
        },
        "visuals": {
          "type": "array",
          "description": "Full paths to GameObjects to disable when picking up this drop.",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Vector3Data": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "x": {
          "type": "number",
          "format": "float"
        },
        "y": {
          "type": "number",
          "format": "float"
        },
        "z": {
          "type": "number",
          "format": "float"
        }
      }
    }
  }
}

=== Hawkbat/OuterWildsRPG/drops/basic_jetpack.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "BASIC_JETPACK",
  "name": "Hatchling's Jetpack",
  "description": "A rocket-powered jetpack. Many a Hearthian has burnt the backs of their legs from using these improperly.",
  "rarity": "uncommon",
  "equipSlot": "jetpack",
  "iconPath": "JETPACK.png",
  "locations": []
}

=== Hawkbat/OuterWildsRPG/drops/basic_stick.json
{
  "$schema": "https://raw.githubusercontent.com/Hawkbat/OuterWildsRPG/main/schemas/drop.schema.json",
  "id": "BASIC_STICK",
  "name": "Roasting Stick",
  "description": "A basic stick, for roasting marshmellows on.",
  "rarity": "common",
  "equipSlot": "stick",
  "locations": [
    {
      "parentPath": "TimberHearth_Body/Sector_TH/Sector_Village/Sector_StartingCamp/Props_StartingCamp/OtherComponentsGroup/Props_HEA_CampsiteLogAssets",
      "position": {
        "x": 0.8133,
        "y": -0.0007,
        "z": 1.6912
      },
      "visuals": [
        "TimberHearth_Body/Sector_TH/Sector_Village/Sector_StartingCamp/Props_StartingCamp/OtherComponentsGroup/Props_HEA_CampsiteLogAssets/Props_HEA_MarshmallowStick",
        "TimberHearth_Body/Sector_TH/Sector_Village/Sector_StartingCamp/Props_StartingCamp/OtherComponentsGroup/Props_HEA_CampsiteLogAssets/Props_HEA_MarshmallowUncoocked1",
        "TimberHearth_Body/Sector_TH/Sector_Village/Sector_StartingCamp/Props_StartingCamp/OtherComponentsGroup/Props_HEA_CampsiteLogAssets/Props_HEA_MarshmallowCanOpened"
      ]
    }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/basic_launcher.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "BASIC_LAUNCHER",
  "name": "Hatchling's Scout Launcher",
  "description": "Launches scouts over long distances. It feels like a weapon, but Slate insists it's safe-ish.",
  "rarity": "uncommon",
  "equipSlot": "launcher",
  "iconPath": "SCOUT_LAUNCHER_EMPTY.png",
  "locations": []
}

=== Hawkbat/OuterWildsRPG/drops/marshmallow.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "MARSHMALLOW",
  "name": "Marshmallow",
  "description": "Can be eaten raw, but much better roasted!",
  "rarity": "common",
  "consumable": true,
  "iconPath": "MARSHMALLOW.png",
  "locations": [],
  "buffs": [
    {
      "heal": { "amount": 0.05 }
    }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/radio_reservoir.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "RADIO_RESERVOIR",
  "name": "Reservoir Cassette",
  "description": "A cassette tape for your ship's radio that reminds you of the Stranger's reservoir.",
  "rarity": "rare",
  "equipSlot": "radio",
  "iconPath": "RECORDER.png",
  "locations": [
    {
      "parentPath": "RingWorld_Body/Sector_RingInterior",
      "position": {
        "x": 117.6118,
        "y": 0.3634071,
        "z": -184.0373
      },
      "rotation": {
        "x": 1.125736,
        "y": 59.84858,
        "z": 90.00004
      }
    }
  ],
  "buffs": [
    { "travelMusic": { "audioType": "RaftTravel_Reservoir" } }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/radio_atp.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "RADIO_ATP",
  "name": "Ash Twin Project Cassette",
  "description": "A cassette tape for your ship's radio that reminds you of a significant discovery.",
  "rarity": "rare",
  "equipSlot": "radio",
  "iconPath": "RECORDER.png",
  "locations": [
    {
      "parentPath": "TimeLoopRing_Body",
      "position": {
        "x": -25.42101,
        "y": 11.22423,
        "z": 0.09000435
      },
      "rotation": {
        "x": 293.9102,
        "y": 110.8885,
        "z": 160.767
      }
    }
  ],
  "buffs": [
    { "travelMusic": { "audioType": "TimeLoopDevice_Ambient" } }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/radio_river.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "RADIO_RIVER",
  "name": "River Cassette",
  "description": "A cassette tape for your ship's radio that reminds you of rafting in the Stranger.",
  "rarity": "uncommon",
  "equipSlot": "radio",
  "iconPath": "RECORDER.png",
  "locations": [
    {
      "parentPath": "RingWorld_Body/Sector_RingInterior",
      "position": {
        "x": -289.08,
        "y": 36.8624,
        "z": -76.24989
      },
      "rotation": {
        "x": 50.63347,
        "y": 51.88524,
        "z": 351.1329
      }
    }
  ],
  "buffs": [
    { "travelMusic": { "audioType": "RaftTravel_River" } }
  ]
}

=== Hawkbat/OuterWildsRPG/drops/basic_scout.json
{
  "$schema": "../schemas/drop.schema.json",
  "id": "BASIC_SCOUT",
  "name": "Hatchling's Scout",
  "description": "The Surveyer Probe Mk. IV, or 'Little Scout.' These devices incorporate borrowed Nomai technology for their recall capability.",
  "rarity": "uncommon",
  "equipSlot": "scout",
  "iconPath": "SCOUT.png",
  "locations": []
}
