=== Hawkbat/OuterWildsRPG/schemas/perk.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "PerkData",
  "type": "object",
  "description": "A perk that can be unlocked by the player using perk points to grant certain passive effects.",
  "additionalProperties": false,
  "required": [
    "id",
    "name"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique internal identifier for this entity. This must not be the same as any other entity of the same type in your mod.",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "description": "The name to display in-game for this entity.",
      "minLength": 1
    },
    "level": {
      "type": "integer",
      "description": "The minimum level requirement to unlock this perk.",
      "format": "int32"
    },
    "iconPath": {
      "type": "string",
      "description": "A file path (relative to your mod's folder) to an image file to use for this perk's icon. Can be shared with other perks."
    },
    "color": {
      "description": "The color to use for this perk's background in-game.",
      "$ref": "#/definitions/ColorData"
    },
    "prereq": {
      "type": "string",
      "description": "The ID of a perk that must be unlocked before this perk becomes available."
    },
    "buffs": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/BuffData"
      }
    },
    "$schema": {
      "type": "string",
      "description": "The schema to validate with"
    }
  },
  "definitions": {
    "ColorData": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "r": {
          "type": "number",
          "format": "float"
        },
        "g": {
          "type": "number",
          "format": "float"
        },
        "b": {
          "type": "number",
          "format": "float"
        },
        "a": {
          "type": "number",
          "format": "float",
          "default": 1.0
        }
      }
    },
    "BuffData": {
      "type": "object",
      "description": "Various possible effects that will apply when the buff is active.",
      "additionalProperties": false,
      "properties": {
        "moveSpeed": {
          "description": "Modifies the player's movement speed.",
          "$ref": "#/definitions/MoveSpeedEffectData"
        },
        "jumpSpeed": {
          "description": "Modifies the player's jump speed.",
          "$ref": "#/definitions/JumpSpeedEffectData"
        },
        "hazardDamage": {
          "description": "Modifies the damage the player takes from various types of hazards.",
          "$ref": "#/definitions/HazardDamageEffectData"
        },
        "translationSpeed": {
          "description": "Modifies the speed at which the player can translate Nomai text.",
          "$ref": "#/definitions/TranslationSpeedEffectData"
        },
        "travelMusic": {
          "description": "Changes the travel music played when flying the ship between planets.",
          "$ref": "#/definitions/TravelMusicEffectData"
        },
        "inventorySpace": {
          "description": "Increases the capacity of the player's inventory.",
          "$ref": "#/definitions/InventorySpaceEffectData"
        },
        "heal": {
          "description": "Restores a percentage of the player's health.",
          "$ref": "#/definitions/HealEffectData"
        },
        "giveDrop": {
          "description": "Adds a drop directly to the player's inventory.",
          "$ref": "#/definitions/GiveDropEffectData"
        },
        "custom": {
          "description": "Defines a custom effect that can be interacted with via the mod API.",
          "$ref": "#/definitions/CustomEffectData"
        }
      }
    },
    "MoveSpeedEffectData": {
      "type": "object",
      "description": "Modifies the player's movement speed.",
      "additionalProperties": false,
      "required": [
        "multiply"
      ],
      "properties": {
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total movement speed by. E.g. a value of 0.25 will result in 25% movement speed, or a 75% reduction.",
          "format": "float",
          "default": 1.0
        }
      }
    },
    "JumpSpeedEffectData": {
      "type": "object",
      "description": "Modifies the player's jump speed.",
      "additionalProperties": false,
      "required": [
        "multiply"
      ],
      "properties": {
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total jump speed by. E.g. a value of 0.25 will result in 25% jump speed, or a 75% reduction.",
          "format": "float",
          "default": 1.0
        }
      }
    },
    "HazardDamageEffectData": {
      "type": "object",
      "description": "Modifies the damage the player takes from various types of hazards.",
      "additionalProperties": false,
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "description": "The type of hazard to modify damage for.",
          "$ref": "#/definitions/HazardType"
        },
        "add": {
          "type": "number",
          "description": "The percentage of the initial damage to add/reduce. E.g. a value of -0.1 means subtract 10% of the base damage from the total.",
          "format": "float",
          "default": 0.0
        },
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total damage by. E.g. a value of 0.25 will result in 25% damage, or a 75% reduction.",
          "format": "float",
          "default": 1.0
        }
      }
    },
    "HazardType": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "All",
        "General",
        "GhostMatter",
        "Heat",
        "Fire",
        "Sandfall",
        "Electricity"
      ],
      "enum": [
        "all",
        "general",
        "ghostMatter",
        "heat",
        "fire",
        "sandfall",
        "electricity"
      ]
    },
    "TranslationSpeedEffectData": {
      "type": "object",
      "description": "Modifies the speed at which the player can translate Nomai text.",
      "additionalProperties": false,
      "properties": {
        "multiply": {
          "type": "number",
          "description": "The percentage to multiply the total translation time by. E.g. a value of 0.25 will result in translating taking 25% of the usual time, or a 75% reduction.",
          "format": "float"
        }
      }
    },
    "TravelMusicEffectData": {
      "type": "object",
      "description": "Changes the travel music played when flying the ship between planets.",
      "additionalProperties": false,
      "required": [
        "audioType"
      ],
      "properties": {
        "audioType": {
          "type": "string",
          "description": "An Outer Wilds AudioType value that will be used as the travel music will this buff is active. See https://nh.outerwildsmods.com/reference/audio_enum.html",
          "minLength": 1
        }
      }
    },
    "InventorySpaceEffectData": {
      "type": "object",
      "description": "Increases the capacity of the player's inventory.",
      "additionalProperties": false,
      "required": [
        "amount"
      ],
      "properties": {
        "amount": {
          "type": "integer",
          "description": "The number of inventory spaces to add.",
          "format": "int32"
        }
      }
    },
    "HealEffectData": {
      "type": "object",
      "description": "Restores a percentage of the player's health.",
      "additionalProperties": false,
      "required": [
        "amount"
      ],
      "properties": {
        "amount": {
          "type": "number",
          "description": "The percentage of total health to restore. E.g. 0.2 will restore 20% of maximum health.",
          "format": "float"
        }
      }
    },
    "GiveDropEffectData": {
      "type": "object",
      "description": "Adds a drop directly to the player's inventory.",
      "additionalProperties": false,
      "required": [
        "drop"
      ],
      "properties": {
        "drop": {
          "type": "string",
          "description": "The unique ID of the drop to give.",
          "minLength": 1
        },
        "amount": {
          "type": "integer",
          "description": "The number of copies to give.",
          "format": "int32",
          "default": 1
        }
      }
    },
    "CustomEffectData": {
      "type": "object",
      "description": "Defines a custom effect that can be interacted with via the mod API.",
      "additionalProperties": false,
      "required": [
        "id",
        "description"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "A custom value that uniquely identifies this effect. Also used as the description's translation key.",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "description": "The text to display in the UI for this effect.",
          "minLength": 1
        }
      }
    }
  }
}

=== Hawkbat/OuterWildsRPG/perks/inventory_space_2.json
{
  "$schema": "../schemas/perk.schema.json",
  "id": "INVENTORY_SPACE_2",
  "name": "Inventory Up II",
  "level": 1,
  "prereq": "INVENTORY_SPACE_1",
  "iconPath": "INVENTORY_SPACE.png",
  "color": { "r": 1, "g": 0.75, "b": 0 },
  "buffs": [
    {
      "inventorySpace": { "amount": 5 }
    }
  ]
}

=== Hawkbat/OuterWildsRPG/perks/inventory_space_5.json
{
  "$schema": "../schemas/perk.schema.json",
  "id": "INVENTORY_SPACE_5",
  "name": "Inventory Up V",
  "level": 1,
  "prereq": "INVENTORY_SPACE_4",
  "iconPath": "INVENTORY_SPACE.png",
  "color": { "r": 1, "g": 0.75, "b": 0 },
  "buffs": [
    {
      "inventorySpace": { "amount": 10 }
    }
  ]
}

=== Hawkbat/OuterWildsRPG/perks/inventory_space_3.json
{
  "$schema": "../schemas/perk.schema.json",
  "id": "INVENTORY_SPACE_3",
  "name": "Inventory Up III",
  "level": 1,
  "prereq": "INVENTORY_SPACE_2",
  "iconPath": "INVENTORY_SPACE.png",
  "color": { "r": 1, "g": 0.75, "b": 0 },
  "buffs": [
    {
      "inventorySpace": { "amount": 5 }
    }
  ]
}

=== Hawkbat/OuterWildsRPG/perks/inventory_space_4.json
{
  "$schema": "../schemas/perk.schema.json",
  "id": "INVENTORY_SPACE_4",
  "name": "Inventory Up IV",
  "level": 1,
  "prereq": "INVENTORY_SPACE_3",
  "iconPath": "INVENTORY_SPACE.png",
  "color": { "r": 1, "g": 0.75, "b": 0 },
  "buffs": [
    {
      "inventorySpace": { "amount": 5 }
    }
  ]
}
